# Generated by Django 5.0.2 on 2024-02-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profskills", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Professions",
            new_name="Profession",
        ),
    ]
